# a rakefile for build the sample corpus

#this is the old-style bash command line we're trying to better
#for dir in *; 
#do  
#    cd $dir;
#    git pull;
#    stub=`git config --get remote.origin.url | sed 's|/[^/]*\.git||'`;  
#    cd -;
#    grep -lR "\(</teiHeader>\|</TEI>\|</TEI.2>\|</fileDesc>\|</bibl>\|<seg \)" $dir | sed "s|\([^/]*\)/\(.*\)|$stub/\1/raw/master/\2|"; 
#done 

task :clean do
     rm "TMP"
end

task :default => [] do
     cp "github_projects.urls", "TMP"
     text=File.open('github_projects.urls').read
     text.gsub!(/\r\n?/, "\n")
     text.each_line do |line|
          git = line.match('https?://github.com/([^/\n\r]*)/([^/\n\r]*)/?')
          git_url = "https://github.com/#{git[1]}/#{git[2]}.git\n"
	  print git_url	
     end
end


