# a rakefile for build the sample corpus

#this is the old-style bash command line we're trying to better
#for dir in *; 
#do  
#    cd $dir;
#    git pull;
#    stub=`git config --get remote.origin.url | sed 's|/[^/]*\.git||'`;  
#    cd -;
#    grep -lR "\(</teiHeader>\|</TEI>\|</TEI.2>\|</fileDesc>\|</bibl>\|<seg \)" $dir | sed "s|\([^/]*\)/\(.*\)|$stub/\1/raw/master/\2|"; 
#done 

#BUILD = ./build/

task :createBuildDirectory => [:clean] do
     directory "./build/"
end

task :clean do

end


task :dothework => [:createBuildDirectory] do
     line_num=0
     text=File.open('xxx.txt').read
     text.gsub!(/\r\n?/, "\n")
     text.each_line do |line|
          print "#{line_num += 1} #{line}"	
     end
end


